const searchArr = [
  {
    district: 'chisinau',
    city: 'chisinau',
    name: 'asm',
    search: 'academiei',
  },
  {
    district: 'chisinau',
    city: 'botanica',
    name: 'DCantemir',
    search: 'dimitrie cantemir|d.cantemir|d. cantemir',
  },
  {
    district: 'chisinau',
    city: 'botanica',
    name: 'MGrecu',
    search: 'grecu',
  },
  {
    district: 'chisinau',
    city: 'buicani',
    name: 'ACantemir',
    search: 'antioh cantemir',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'prometeu',
    search: 'prometeu',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'MEliade',
    search: 'eliade',
  },
  {
    district: 'bender',
    city: 'bender',
    name: 'AlexanruCelBun',
    search: 'alexandru cel bun',
  },
  {
    district: 'ribnita',
    city: 'ribnita',
    name: 'evrika',
    search: 'evrika',
  },
  {
    district: 'chisinau',
    city: 'botanica',
    name: 'MEminescu',
    search: 'eminescu',
  },
  {
    district: 'tiraspol',
    city: 'tiraspol',
    name: 'LBlaga',
    search: 'blaga',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'ElimulNou',
    search: 'elimul',
  },
  {
    district: 'chisinau',
    city: 'riscani',
    name: 'ARusso',
    search: 'russo',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'evrica',
    search: 'evrica',
  },
  {
    district: 'chisinau',
    city: 'riscani',
    name: 'LimbiModerne',
    search: 'liceul de limbi moderne şi management',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'columna',
    search: 'columna',
  },
  {
    district: 'ialoveni',
    city: 'bardar',
    name: 'ADavid',
    search: 'aurel david',
  },
  {
    district: 'chisinau',
    city: 'stauceni',
    name: 'DVoda',
    search: 'dragoş vodă',
  },
  {
    district: 'edinet',
    city: 'edinet',
    name: 'SeminarDeFete',
    search: 'seminarul',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'NVGogol',
    search: 'gogol',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'APuskin',
    search: 'puşkin',
  },
  {
    district: 'chisinau',
    city: 'riscani',
    name: 'ICreanga',
    search: 'creangă',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'SpiruHaret',
    search: 'haret',
  },
  {
    district: 'balti',
    city: 'balti',
    name: 'MEminescu',
    search: 'eminescu',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'DanteAlighieri',
    search: 'alighieri',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'NDadiani',
    search: 'dadiani',
  },
  {
    district: 'causeni',
    city: 'causeni',
    name: 'MEminescu',
    search: 'eminescu',
  },
  {
    district: 'causeni',
    city: 'causeni',
    name: 'AMateevici',
    search: 'mateevici',
  },
  {
    district: 'chisinau',
    city: 'botanica',
    name: 'LRebreanu',
    search: 'rebreanu',
  },
  {
    district: 'gagauzia',
    city: 'comrat',
    name: 'GAGaidarji',
    search: 'gaidarji',
  },
  {
    district: 'balti',
    city: 'balti',
    name: 'DCantemir',
    search: 'dimitrie cantemir|d.cantemir|d. cantemir',
  },
  {
    district: 'chisinau',
    city: 'botanica',
    name: 'PMovila',
    search: 'movilă',
  },
  {
    district: 'chisinau',
    city: 'botanica',
    name: 'NIorga',
    search: 'iorga',
  },
  {
    district: 'gagauzia',
    city: 'comrat',
    name: 'MEminescu',
    search: 'eminescu',
  },
  {
    district: 'chisinau',
    city: 'centru',
    name: 'litterarum',
    search: 'litterarum',
  },
  {
    district: 'chisinau',
    city: 'buiucani',
    name: 'orizont',
    search: 'orizont',
  },
  {
    district: 'chisinau',
    city: 'riscani',
    name: 'socrate',
    search: 'socrate',
  },
  {
    district: 'chisinau',
    city: 'centru',
    name: 'GAsachi',
    search: 'asachi',
  },
  {
    district: 'chisinau',
    city: 'chisinau',
    name: 'SRahmaninov',
    search: 'rahmaninov',
  },
  {
    district: 'aneniinoi',
    city: 'aneniinoi',
    name: 'MEminescu',
    search: 'eminescu',
  },
  {
    district: 'ungheni',
    city: 'ungheni',
    name: 'VAlecsandri',
    search: 'alecsandri',
  },
];

module.exports = searchArr;
